FROM golang:latest AS builder
ENV GO111MODULE=on

WORKDIR /trade-bot-task
COPY . .

RUN go mod tidy
RUN go build -o ./bin/trade-bot-task ./cmd/task

FROM ubuntu:latest

ENV ENV="local"

RUN apt update && apt install -y libpq5 ca-certificates curl

WORKDIR /app

COPY --from=builder /trade-bot-task/bin/trade-bot-task .
COPY --from=builder /trade-bot-task/config.default.toml .

RUN chmod a+x ./trade-bot-task

EXPOSE 8080

ENTRYPOINT ["./trade-bot-task","run"]
